apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: scc-templates.pkg.maki.lol.0.0.1
spec:
  refName: scc-templates.pkg.maki.lol
  version: 0.0.1
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        excluded_templates:
          type: array
          description: List of templates to exclude from the installation (e.g. ['git-writer'])
          items:
            type: string
            default: ""
          default: []
        storage_class_name:
          type: string
          description: Storage class name of the cache
          default: ""
        cache_size:
          type: string
          description: Storage size for the cache
          default: 2Gi
        service_account:
          type: string
          description: Name of the service account that creates persistent volume claims for the cache via App CR.
          default: default
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/making/scc-templates-bundle:0.0.1
      template:
      - ytt: {}
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp:
          rawOptions:
          - --wait-timeout=5m
          - --diff-changes=true
          inspect:
            rawOptions:
            - --tree=true
